### ISSUE TITLE
Kbin.social account not working

### ISSUE THREAD

**Issue by sxe** [daniel-lxs/BotIt#18]
Hey, 
I created a kbin.social account but when trying to start the bot I get an error message:
 

> [a@eos Botit]$ npm start
>
>> botlt@0.1.0 start
>> node dist/scheduler.js
>
>[ERROR] [LEMMY] Error while trying to login, host might be down
>[ERROR] [SCHEDULER] An error occurred: Error: FetchError: invalid json response body at https://kbin.social/api/v3/user/login reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Is it supposed to work with kbin accounts? 

Cheers

**Comment by daniel-lxs** [comment]
Hello! It doesn't work with kbin accounts yet since kbin doesn't have an API (for now). 

But you should be able to use any lemmy account, just make sure you don't mark that account as "bot account" on lemmy, that will make the posts not show up on kbin.

Let me know if you have any other questions or suggestions!

**Comment by sxe** [comment]
Hey! Thanks for the reply. 
That's unfortunate. I have to think about it again then since I made the decision to not support lemmy directly. I am not in line with their political believes at all and don't want to support that platform even indirectly.

**Comment by daniel-lxs** [comment]
I understand, as far as I know there are other instances that are run by different admins all together, since it's open source everyone can fire up a lemmy instance.
Maybe if you find one you could use it.

Thanks for the comments!

**Comment by sxe** [comment]
Yeah I might do that. Thanks
Case closed anyways. :)
