### ISSUE TITLE
Possible to mirror to reddit as well?

### ISSUE THREAD

**Issue by Hedwig7s** [daniel-lxs/BotIt#19]
The Reddit API is only pay-for for commercial use so a financial limitation isn't a problem

**Comment by daniel-lxs** [comment]
Crosspost from lemmy to reddit? I would say for this project it is outside the current scope. I just don't think reddit needs more content.

**Comment by Hedwig7s** [comment]
> Crosspost from lemmy to reddit? I would say for this project it is outside the current scope. I just don't think reddit needs more content.

Aw c'mon the main struggle is moving from Reddit to Lemmy because of stubborn users not wanting to move it would be nice to be able to go the other way
