### ISSUE TITLE
Latest update seems to result in problematic post titles

### ISSUE THREAD

**Issue by Zamboniman** [daniel-lxs/BotIt#20]
Before the latest changes, the bot appeared to use the post title of the original Reddit post. Now it seems to do otherwise. This resulted in the unhelpful post title of "Twitter / ?" for a post in calgary_flames@lemmy.ca instead of "[Salim Nadim Valji] Hearing Mitch Love has had interest from multiple teams as an assistant coach." (I re-edited it manually). Likewise, a post in electric_scooters@lemmy.ca became entitled "Blocked" (Maybe something to do with the sub being marked NSFW as part of the protest?) instead of "DIY 90MPH scooter update #3! Chassis fully completed & painted asides from top deck, planning on an aluminum + carbon fiber build for the top :)" Again, I edited this manually.

**Comment by daniel-lxs** [comment]
Will check this out, thank you for reporting it

**Comment by daniel-lxs** [comment]
It should be back to normal now, please pull the changes and rebuild :)

**Comment by Zamboniman** [comment]
That was fast!!  Thanks, I'll give it a try.
