### ISSUE TITLE
Suppress cross posts and discussion posts

### ISSUE THREAD

**Issue by poVoq** [daniel-lxs/BotIt#23]
Cross posts are usually quite spammy and scraping discussion posts seems a bit pointless. Maybe those can be suppressed?

**Comment by samuk** [comment]
+1 Maybe we could have a block or allow list that excluded all posts that link directly to reddit.com? Just use it to harvest good links to third party sites?

**Comment by daniel-lxs** [comment]
Added on [b8f43bc](https://github.com/daniel-lxs/BotIt/commit/b8f43bcd814713b9adbfb5f2d291f103a730ae5a), you can now use regular expressions to exclude urls, check https://github.com/daniel-lxs/BotIt#readme to learn how to use it.

**Comment by poVoq** [comment]
Excellent idea. Thanks a lot!
