### ISSUE TITLE
Feature request: Only post if it's quiet

### ISSUE THREAD

**Issue by samuk** [daniel-lxs/BotIt#25]
How feasible would it be to additionally query the Lemmy API for the community you were posting into and to only post if there was no posts in the previous -user defined timeperiod- 

As a community owner I may be happy for a bot to 'fill in the gaps' between human posts, but where a human has posted in the previous ~1hr I may want to give that human post time to attract views and comments.

**Comment by daniel-lxs** [comment]
Let me know how it goes!

**Comment by samuk** [comment]
Nice thanks! Just updated. I'll let you know..
